spring:
  application:
    name: customer-service



  data:
    mongodb:
      host: mongodb.microservices-ecommerce #.svc.cluster.local
      port: 27017
      username: wail
      password: wail
      database: customer

server:
  port: 7070


