spring:
  application:
    name: payment-service

  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #  url: jdbc:postgresql://postgresql-service.db.svc.cluster.local:5432/payment
  #  username: postgres
  #  password: adaptive1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.microservices-ecommerce:5432/product #.svc.cluster.local
    username: wail
    password: wail

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka.microservices-ecommerce:9092 # where to initially connect to the kafka cluster
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.adaptive.ecommerce.kafka.payment.PaymentConfirmation
        spring.json.add.type.headers: true  # This tells Kafka to add a type header
    
server:
  port: 7090
